version: '3.8'
services:
  phpmyadmin:
    container_name: eclaim_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root

  db:
    container_name: eclaim_db
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e_claim
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - localhost
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: eclaim_api
    build:
      context: ./api-e-claim-2.0
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '8000:80'
    volumes:
      - ./api-e-claim-2.0:/var/www/html:delegated
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://root:root@db:3306/e_claim
      CLAIM_USER_DATABASE_URL: mysql://root:root@db:3306/claim_user_db

  client:
    container_name: eclaim_client
    build:
      context: ./client-e-claim-2.0
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - '4200:4200'
    volumes:
      - ./client-e-claim-2.0:/app:delegated
      - client_node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    command: npm run start -- --host 0.0.0.0 --poll=2000

volumes:
  db_data: {}
  client_node_modules: {}
